// hash: #151556f9
// @formatter:off

package metacode.core.parser.data.serializers

import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import metacode.api.parser.data.models.*
import metacode.api.parser.data.models.OptionalParserExpression
import metacode.core.parser.data.builders.OptionalParserExpressionBuilder
import metacode.core.parser.data.models.*
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object OptionalParserExpressionSerializer : ModelSerializer<OptionalParserExpression, OptionalParserExpression>
{
	private val endOfObject: Int = 0
	
	private val expressionIndex: Int = 1
	
	private val isGreedyIndex: Int = 2
	
	override val modelId: UUID
		get() = OptionalParserExpression.serializationKey
	
	override val dataClass: Class<OptionalParserExpression>
		get() = OptionalParserExpression::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: OptionalParserExpression)
	{
		stream.writeUnsignedVarInt(expressionIndex)
		schema.serialize(serializationContext, stream, entity.expression)
		
		stream.writeUnsignedVarInt(isGreedyIndex)
		schema.serialize(serializationContext, stream, entity.isGreedy)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): OptionalParserExpression
	{
		var expression: ParserExpression? = null
		var isGreedy: Boolean? = true
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultOptionalParserExpression(
					expression!!,
					isGreedy!!,
				)
				expressionIndex -> expression = schema.deserialize(deserializationContext, stream)
				isGreedyIndex -> isGreedy = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
