// hash: #93e640c7
// @formatter:off

package metacode.core.parser.data.serializers

import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import metacode.api.parser.data.models.*
import metacode.api.parser.data.models.SequenceParserExpression
import metacode.core.parser.data.builders.SequenceParserExpressionBuilder
import metacode.core.parser.data.models.*
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object SequenceParserExpressionSerializer : ModelSerializer<SequenceParserExpression, SequenceParserExpression>
{
	private val endOfObject: Int = 0
	
	private val expressionsIndex: Int = 1
	
	override val modelId: UUID
		get() = SequenceParserExpression.serializationKey
	
	override val dataClass: Class<SequenceParserExpression>
		get() = SequenceParserExpression::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: SequenceParserExpression)
	{
		stream.writeUnsignedVarInt(expressionsIndex)
		schema.serialize(serializationContext, stream, entity.expressions)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): SequenceParserExpression
	{
		var expressions: MutableList<ParserExpression>? = mutableListOf()
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultSequenceParserExpression(
					expressions!!.toMutableList(),
				)
				expressionsIndex -> expressions = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
