// hash: #f7bb1b61
// @formatter:off

package metacode.core.parser.data.serializers

import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import metacode.api.parser.data.models.*
import metacode.api.parser.data.models.TypeParserExpression
import metacode.core.parser.data.builders.TypeParserExpressionBuilder
import metacode.core.parser.data.models.*
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object TypeParserExpressionSerializer : ModelSerializer<TypeParserExpression, TypeParserExpression>
{
	private val endOfObject: Int = 0
	
	private val typeNameIndex: Int = 1
	
	override val modelId: UUID
		get() = TypeParserExpression.serializationKey
	
	override val dataClass: Class<TypeParserExpression>
		get() = TypeParserExpression::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: TypeParserExpression)
	{
		stream.writeUnsignedVarInt(typeNameIndex)
		schema.serialize(serializationContext, stream, entity.typeName)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): TypeParserExpression
	{
		var typeName: String? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultTypeParserExpression(
					typeName!!,
				)
				typeNameIndex -> typeName = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
