// hash: #2bd3d7aa
// data: serializationKey:bdb54467-c984-4d86-80e9-5dcf388feed2
// @formatter:off

package metacode.api.lexer.data.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq

import metacode.api.lexer.sources.CharToken

// @tomplot:customCode:end
// @formatter:off

interface AnyOfLexerExpression : BitSerializable, LexerExpression, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("bdb54467-c984-4d86-80e9-5dcf388feed2")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val expressions: List<LexerExpression>
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is AnyOfLexerExpression) return false
		
		if (expressions != other.expressions) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(expressions)
	
	override fun toJson(): String =
		"""{"expressions":${expressions.toJsonString()}}"""
	
	override fun duplicate(): AnyOfLexerExpression
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	
	override fun findMatches(tokens: List<CharToken>, fromIndex: Int): Sequence<String> =
		expressions
			.asSequence()
			.flatMap { it.findMatches(tokens, fromIndex) }
	
	override fun toExpressionString(): String =
		expressions.joinToString(" | ") { it.toExpressionString() }
	
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
