// hash: #0196d0a7
// data: serializationKey:3a68fbe5-2a92-4bd2-a07c-e13420e510fc
// @formatter:off

package metacode.api.lexer.data.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface LexerRuleMetaData : BitSerializable, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("3a68fbe5-2a92-4bd2-a07c-e13420e510fc")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val isSkippingRule: Boolean
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is LexerRuleMetaData) return false
		
		if (isSkippingRule != other.isSkippingRule) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(isSkippingRule)
	
	override fun toJson(): String =
		"""{"isSkippingRule":${isSkippingRule.toJsonString()}}"""
	
	override fun duplicate(): LexerRuleMetaData
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
