// hash: #09359c39
// data: serializationKey:09805e55-c394-491b-ac60-6a92e3013b47
// @formatter:off

package metacode.api.lexer.data.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface LexerRule : BitSerializable, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("09805e55-c394-491b-ac60-6a92e3013b47")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val name: String
	
	val metaData: LexerRuleMetaData
	
	val expression: LexerExpression
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is LexerRule) return false
		
		if (name != other.name) return false
		if (metaData != other.metaData) return false
		if (expression != other.expression) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(name)
			.with(metaData)
			.with(expression)
	
	override fun toJson(): String =
		"""{"name":${name.toJsonString()},"metaData":${metaData.toJsonString()},"expression":${expression.toJsonString()}}"""
	
	override fun duplicate(): LexerRule
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
