// hash: #221cedda
// data: serializationKey:dadcbd8c-a873-47b7-8725-dc7cbf5ec93f
// @formatter:off

package metacode.api.lexer.data.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq

import metacode.api.lexer.sources.CharToken
import utils.common.append

// @tomplot:customCode:end
// @formatter:off

interface OptionalLexerExpression : BitSerializable, LexerExpression, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("dadcbd8c-a873-47b7-8725-dc7cbf5ec93f")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val expression: LexerExpression
	
	val isGreedy: Boolean
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is OptionalLexerExpression) return false
		
		if (expression != other.expression) return false
		if (isGreedy != other.isGreedy) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(expression)
			.with(isGreedy)
	
	override fun toJson(): String =
		"""{"expression":${expression.toJsonString()},"isGreedy":${isGreedy.toJsonString()}}"""
	
	override fun duplicate(): OptionalLexerExpression
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	
	override fun findMatches(tokens: List<CharToken>, fromIndex: Int): Sequence<String> =
		expression
			.findMatches(tokens, fromIndex)
			.append("")
	
	override fun toExpressionString(): String =
		expression.toExpressionString() + "?"
	
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
