// hash: #812d4c2f
// @formatter:off

package metacode.core.lexer.data.serializers

import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import metacode.api.lexer.data.models.*
import metacode.api.lexer.data.models.LexerRuleMetaData
import metacode.core.lexer.data.builders.LexerRuleMetaDataBuilder
import metacode.core.lexer.data.models.*
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object LexerRuleMetaDataSerializer : ModelSerializer<LexerRuleMetaData, LexerRuleMetaData>
{
	private val endOfObject: Int = 0
	
	private val isSkippingRuleIndex: Int = 1
	
	override val modelId: UUID
		get() = LexerRuleMetaData.serializationKey
	
	override val dataClass: Class<LexerRuleMetaData>
		get() = LexerRuleMetaData::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: LexerRuleMetaData)
	{
		stream.writeUnsignedVarInt(isSkippingRuleIndex)
		schema.serialize(serializationContext, stream, entity.isSkippingRule)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): LexerRuleMetaData
	{
		var isSkippingRule: Boolean? = false
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultLexerRuleMetaData(
					isSkippingRule!!,
				)
				isSkippingRuleIndex -> isSkippingRule = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
