// hash: #cd744af8
// @formatter:off

package metacode.core.lexer.data.serializers

import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import metacode.api.lexer.data.models.*
import metacode.api.lexer.data.models.RepeatingLexerExpression
import metacode.core.lexer.data.builders.RepeatingLexerExpressionBuilder
import metacode.core.lexer.data.models.*
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object RepeatingLexerExpressionSerializer : ModelSerializer<RepeatingLexerExpression, RepeatingLexerExpression>
{
	private val endOfObject: Int = 0
	
	private val expressionIndex: Int = 1
	
	private val minimumMatchesIndex: Int = 2
	
	private val isGreedyIndex: Int = 3
	
	override val modelId: UUID
		get() = RepeatingLexerExpression.serializationKey
	
	override val dataClass: Class<RepeatingLexerExpression>
		get() = RepeatingLexerExpression::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: RepeatingLexerExpression)
	{
		stream.writeUnsignedVarInt(expressionIndex)
		schema.serialize(serializationContext, stream, entity.expression)
		
		stream.writeUnsignedVarInt(minimumMatchesIndex)
		schema.serialize(serializationContext, stream, entity.minimumMatches)
		
		stream.writeUnsignedVarInt(isGreedyIndex)
		schema.serialize(serializationContext, stream, entity.isGreedy)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): RepeatingLexerExpression
	{
		var expression: LexerExpression? = null
		var minimumMatches: Int? = null
		var isGreedy: Boolean? = true
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultRepeatingLexerExpression(
					expression!!,
					minimumMatches!!,
					isGreedy!!,
				)
				expressionIndex -> expression = schema.deserialize(deserializationContext, stream)
				minimumMatchesIndex -> minimumMatches = schema.deserialize(deserializationContext, stream)
				isGreedyIndex -> isGreedy = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
