// hash: #f8b00196
// @formatter:off

package metacode.core.lexer.data.builders

import metacode.api.lexer.data.models.*
import metacode.core.lexer.data.models.DefaultAnyOfLexerExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class AnyOfLexerExpressionBuilder
{
	var expressions: MutableList<LexerExpression>? = mutableListOf()
	
	fun build(): AnyOfLexerExpression =
		DefaultAnyOfLexerExpression(
			expressions!!.toMutableList(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
