// hash: #d9692045
// @formatter:off

package metacode.core.lexer.data.builders

import metacode.api.lexer.data.models.*
import metacode.core.lexer.data.models.DefaultCharacterGroupLexerExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class CharacterGroupLexerExpressionBuilder
{
	var characters: MutableSet<Char>? = mutableSetOf()
	
	var isPositive: Boolean? = true
	
	fun build(): CharacterGroupLexerExpression =
		DefaultCharacterGroupLexerExpression(
			characters!!.toMutableSet(),
			isPositive!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
