// hash: #40d50c4e
// @formatter:off

package metacode.core.lexer.data.builders

// Generated by BitBlock version 1.0.0

object MetaCodeLexerBuilderFacade
{
	fun buildAnyOfLexerExpression(body: AnyOfLexerExpressionBuilder.() -> Unit) =
		AnyOfLexerExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildCharacterGroupLexerExpression(body: CharacterGroupLexerExpressionBuilder.() -> Unit) =
		CharacterGroupLexerExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildLiteralLexerExpression(body: LiteralLexerExpressionBuilder.() -> Unit) =
		LiteralLexerExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildOptionalLexerExpression(body: OptionalLexerExpressionBuilder.() -> Unit) =
		OptionalLexerExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildRepeatingLexerExpression(body: RepeatingLexerExpressionBuilder.() -> Unit) =
		RepeatingLexerExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildSequenceLexerExpression(body: SequenceLexerExpressionBuilder.() -> Unit) =
		SequenceLexerExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildWildcardLexerExpression(body: WildcardLexerExpressionBuilder.() -> Unit) =
		WildcardLexerExpressionBuilder()
			.apply(body)
			.build()
	
	fun buildLexerRule(body: LexerRuleBuilder.() -> Unit) =
		LexerRuleBuilder()
			.apply(body)
			.build()
	
	fun buildLexerRuleMetaData(body: LexerRuleMetaDataBuilder.() -> Unit) =
		LexerRuleMetaDataBuilder()
			.apply(body)
			.build()
}
// @formatter:on
