// hash: #b60a94ff
// @formatter:off

package metacode.core.lexer.data.builders

import metacode.api.lexer.data.models.*
import metacode.core.lexer.data.models.DefaultRepeatingLexerExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class RepeatingLexerExpressionBuilder
{
	var expression: LexerExpression? = null
	
	var minimumMatches: Int? = null
	
	var isGreedy: Boolean? = true
	
	fun build(): RepeatingLexerExpression =
		DefaultRepeatingLexerExpression(
			expression!!,
			minimumMatches!!,
			isGreedy!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
