// hash: #d00c6d08
// @formatter:off

package metacode.core.parser.data.models

import metacode.api.parser.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn

import metacode.api.parser.context.MatchContext

// @tomplot:customCode:end
// @formatter:off

data class DefaultRuleOption(
	override val name: String,
	override val expression: ParserExpression,
) : RuleOption
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultRuleOption =
		copy(
			name = name,
			expression = expression.duplicate(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	
	override fun isLeftRecursiveTo(context: MatchContext, name: CharSequence): Boolean =
		expression.isLeftRecursiveTo(context, name)
	
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
