// hash: #3ad7932f
// @formatter:off

package metacode.core.parser.data.models

import metacode.api.parser.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn

import metacode.core.parser.data.commonMergeResults
import metacode.core.parser.results.ExpressionResultImpl
import metacode.api.lexer.MetaCodeToken
import metacode.api.parser.context.MatchContext
import metacode.api.parser.results.ExpressionResult
import metacode.api.parser.results.RuleResult
import utils.common.append
import utils.common.emptyManyValuesMap

// @tomplot:customCode:end
// @formatter:off

data class DefaultOptionalParserExpression(
	override val expression: ParserExpression,
	override val isGreedy: Boolean = true,
) : OptionalParserExpression
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultOptionalParserExpression =
		copy(
			expression = expression.duplicate(),
			isGreedy = isGreedy,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	
	override fun findMatches(context: MatchContext, tokens: List<MetaCodeToken>, fromIndex: Int): Sequence<ExpressionResult> =
		expression
			.findMatches(context, tokens, fromIndex)
			.append(ExpressionResultImpl(this, fromIndex, fromIndex, emptyList(), null, emptyManyValuesMap()))
			.map { ExpressionResultImpl(this, it.startIndex, it.endIndex, it.tokens, it.option, it.members) }
	
	override fun findMatches(context: MatchContext, tokens: List<MetaCodeToken>, fromIndex: Int, feed: List<RuleResult>): Sequence<ExpressionResult> =
		expression
			.findMatches(context, tokens, fromIndex, feed)
			.append(ExpressionResultImpl(this, fromIndex, fromIndex, emptyList(), null, emptyManyValuesMap()))
			.map { ExpressionResultImpl(this, it.startIndex, it.endIndex, it.tokens, it.option, it.members) }
	
	override fun isLeftRecursiveTo(context: MatchContext, name: CharSequence): Boolean =
		expression.isLeftRecursiveTo(context, name)
	
	override fun toGrammarString(): String =
		"${expression.toGrammarString()}?"
	
	override fun mergeResults(results: List<ExpressionResult>, tokens: List<MetaCodeToken>, fromIndex: Int): ExpressionResult =
		commonMergeResults(results, tokens, fromIndex)
	
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
