// hash: #44876bee
// @formatter:off

package metacode.core.parser.data.builders

import metacode.api.parser.data.models.*
import metacode.core.parser.data.models.DefaultAnyOfParserExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class AnyOfParserExpressionBuilder
{
	var expressions: MutableList<ParserExpression>? = mutableListOf()
	
	fun build(): AnyOfParserExpression =
		DefaultAnyOfParserExpression(
			expressions!!.toMutableList(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
