// hash: #975f0ac9
// @formatter:off

package metacode.core.parser.data.builders

import metacode.api.parser.data.models.*
import metacode.core.parser.data.models.DefaultMultiOptionRule

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class MultiOptionRuleBuilder
{
	var name: String? = null
	
	var options: MutableList<RuleOption>? = mutableListOf()
	
	fun build(): MultiOptionRule =
		DefaultMultiOptionRule(
			name!!,
			options!!.toMutableList(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
