// hash: #ddca5614
// @formatter:off

package metacode.core.parser.data.builders

import metacode.api.parser.data.models.*
import metacode.core.parser.data.models.DefaultOptionalParserExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class OptionalParserExpressionBuilder
{
	var expression: ParserExpression? = null
	
	var isGreedy: Boolean? = true
	
	fun build(): OptionalParserExpression =
		DefaultOptionalParserExpression(
			expression!!,
			isGreedy!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
