// hash: #4b95042b
// @formatter:off

package metacode.core.parser.data.builders

import metacode.api.parser.data.models.*
import metacode.core.parser.data.models.DefaultRepeatingParserExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class RepeatingParserExpressionBuilder
{
	var expression: ParserExpression? = null
	
	var minimumMatches: Int? = null
	
	var isGreedy: Boolean? = true
	
	fun build(): RepeatingParserExpression =
		DefaultRepeatingParserExpression(
			expression!!,
			minimumMatches!!,
			isGreedy!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
