// hash: #2806d604
// @formatter:off

package metacode.core.parser.data.builders

import metacode.api.parser.data.models.*
import metacode.core.parser.data.models.DefaultRuleParserExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class RuleParserExpressionBuilder
{
	var ruleName: String? = null
	
	var prefix: String? = null
	
	fun build(): RuleParserExpression =
		DefaultRuleParserExpression(
			ruleName!!,
			prefix,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
