// hash: #ae6fa0ba
// @formatter:off

package metacode.core.parser.data.builders

import metacode.api.parser.data.models.*
import metacode.core.parser.data.models.DefaultSequenceParserExpression

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class SequenceParserExpressionBuilder
{
	var expressions: MutableList<ParserExpression>? = mutableListOf()
	
	fun build(): SequenceParserExpression =
		DefaultSequenceParserExpression(
			expressions!!.toMutableList(),
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
