// hash: #73adc77b
// data: serializationKey:fcb84368-3397-4153-b93e-792061f8202e
// @formatter:off

package metacode.api.parser.data.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface AnyOfParserExpression : BitSerializable, ParserExpression, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("fcb84368-3397-4153-b93e-792061f8202e")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val expressions: List<ParserExpression>
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is AnyOfParserExpression) return false
		
		if (expressions != other.expressions) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(expressions)
	
	override fun toJson(): String =
		"""{"expressions":${expressions.toJsonString()}}"""
	
	override fun duplicate(): AnyOfParserExpression
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
