// hash: #0530267c
// data: serializationKey:61ea3f3e-954f-4973-b225-817481d8648f
// @formatter:off

package metacode.api.parser.data.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface LiteralParserExpression : BitSerializable, ParserExpression, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("61ea3f3e-954f-4973-b225-817481d8648f")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val query: String
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is LiteralParserExpression) return false
		
		if (query != other.query) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(query)
	
	override fun toJson(): String =
		"""{"query":${query.toJsonString()}}"""
	
	override fun duplicate(): LiteralParserExpression
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
