// hash: #685d10ce
// @formatter:off

package metacode.api.parser.data.models

import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph

import metacode.api.lexer.MetaCodeToken
import metacode.api.parser.context.MatchContext
import metacode.api.parser.results.RuleResult

// @tomplot:customCode:end
// @formatter:off

sealed interface ParserRule : BitSerializable, Jsonable
{
	val name: String
	
	override fun duplicate(): ParserRule
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	
	fun findMatches(context: MatchContext, tokens: List<MetaCodeToken>, fromIndex: Int): Sequence<RuleResult>
	
	fun isLeftRecursiveTo(context: MatchContext, name: CharSequence): Boolean
	
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
