// hash: #54faca8f
// @formatter:off

package metacode.api.parser.data.models

import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph

import metacode.api.lexer.MetaCodeToken
import metacode.api.parser.context.MatchContext
import metacode.api.parser.results.ExpressionResult
import metacode.api.parser.results.RuleResult

// @tomplot:customCode:end
// @formatter:off

sealed interface ParserExpression : BitSerializable, Jsonable
{
	override fun duplicate(): ParserExpression
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	
	fun findMatches(context: MatchContext, tokens: List<MetaCodeToken>, fromIndex: Int): Sequence<ExpressionResult>
	
	fun findMatches(context: MatchContext, tokens: List<MetaCodeToken>, fromIndex: Int, feed: List<RuleResult>): Sequence<ExpressionResult>
	
	fun isLeftRecursiveTo(context: MatchContext, name: CharSequence): Boolean
	
	fun toGrammarString(): String
	
	fun mergeResults(results: List<ExpressionResult>, tokens: List<MetaCodeToken>, fromIndex: Int): ExpressionResult
	
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
