// hash: #3bf6fa4e
// data: serializationKey:500fbfa2-b9a8-4c56-b629-4ca90f3eceb7
// @formatter:off

package metacode.api.parser.data.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface SequenceParserExpression : BitSerializable, ParserExpression, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("500fbfa2-b9a8-4c56-b629-4ca90f3eceb7")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val expressions: List<ParserExpression>
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is SequenceParserExpression) return false
		
		if (expressions != other.expressions) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(expressions)
	
	override fun toJson(): String =
		"""{"expressions":${expressions.toJsonString()}}"""
	
	override fun duplicate(): SequenceParserExpression
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
