// hash: #7dda8e80
// data: serializationKey:b2d61f32-4197-4d88-ad79-772e21b3f858
// @formatter:off

package metacode.api.parser.data.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface SimpleRule : BitSerializable, ParserRule, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("b2d61f32-4197-4d88-ad79-772e21b3f858")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	override val name: String
	
	val expression: ParserExpression
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is SimpleRule) return false
		
		if (name != other.name) return false
		if (expression != other.expression) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(name)
			.with(expression)
	
	override fun toJson(): String =
		"""{"name":${name.toJsonString()},"expression":${expression.toJsonString()}}"""
	
	override fun duplicate(): SimpleRule
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
