// hash: #0fd0885b
// data: serializationKey:a12db472-b105-4312-9723-dd9856ba2bcc
// @formatter:off

package metacode.api.parser.data.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface TypeParserExpression : BitSerializable, ParserExpression, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("a12db472-b105-4312-9723-dd9856ba2bcc")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val typeName: String
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is TypeParserExpression) return false
		
		if (typeName != other.typeName) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(typeName)
	
	override fun toJson(): String =
		"""{"typeName":${typeName.toJsonString()}}"""
	
	override fun duplicate(): TypeParserExpression
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
