// hash: #ce483740
// @formatter:off

package metacode.core.lexer.data.models

import metacode.api.lexer.data.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultRepeatingLexerExpression(
	override val expression: LexerExpression,
	override val minimumMatches: Int,
	override val isGreedy: Boolean = true,
) : RepeatingLexerExpression
{
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultRepeatingLexerExpression =
		copy(
			expression = expression.duplicate(),
			minimumMatches = minimumMatches,
			isGreedy = isGreedy,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
